print("About Me!")
print("Name: V.Janani")
print("Age: 23")
print("Location: Sivagangai")
print("Education: B.Sc. Computer Science")
print("College: Raja Doraisingam Government Arts and Science College")
print("Education: Diploma in Pharmacy")
print("College: Ultra College of Pharmacy")
print("Technical Skills: Python, SQL, Excel, Pandas, Numpy, PowerBI")
print("Strength: Self-Learner")
print("Weakness: Multi-tasking")
print("Goal: “My goal is to secure a position as a Data Analyst in a reputable company")
print("Hobbies: Reading Books")